name: Docs checks

on: [push, pull_request]

jobs:
  linting:
    name: "Lint markdown files"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "docs/**/*.mdx"

  mintlify:
    name: "Validate Mintlify site"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Validate build
        run: npx -y mint@latest validate

      - name: Check for broken links
        run: npx -y mint@latest broken-links
